// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ESC_Core","status":true,"description":"[ESC] 逃离千禧年核心系统 - 管理游戏全局状态和数据","parameters":{}},
{"name":"ESC_UI_HUD","status":true,"description":"[ESC] 探索界面HUD - 显示玩家状态、技能栏、快捷道具栏","parameters":{}},
{"name":"ESC_Equipment","status":true,"description":"[ESC] 装备系统 - 5部位装备、技能关联","parameters":{}},
{"name":"ESC_Backpack","status":true,"description":"[ESC] 背包系统 - 不规则网格、拖拽、快捷栏绑定","parameters":{}},
{"name":"ESC_VisualEffects","status":true,"description":"[ESC] 怪核视觉效果 - 滤镜、色调、VHS效果、氛围营造","parameters":{"enableVHS":"true","enableNoise":"true","enableVignette":"true","enableChroma":"false","enableCRTCurvature":"true","noiseIntensity":"0.08","vignetteIntensity":"0.4","scanlineOpacity":"0.2","crtCurvature":"0.25","flickerIntensity":"0"}},
{"name":"ESC_Containers","status":true,"description":"[ESC] 容器系统 - 场景容器、物品收集、容器界面","parameters":{"interactionRange":"48","autoSaveContainers":"true"}},
{"name":"ESC_Physics","status":true,"description":"[ESC] 物理系统 - 重力、跳跃、平台碰撞","parameters":{"gravity":"0.5","jumpPower":"8","maxFallSpeed":"10","enableDebug":"false"}},
{"name":"ESC_PixelCollision","status":true,"description":"[ESC] 像素级碰撞检测 - 基于PNG图片大小判定事件触发","parameters":{"triggerDistance":"32","playerHitboxScale":"0.8","eventHitboxScale":"0.9","enableDebug":"false"}},
{"name":"ESC_FixedParallax","status":true,"description":"[ESC] 固定远景 - 让远景图作为地图背景而非视差效果","parameters":{}}
];
